feign:
  sentinel:
    enabled: true

spring:
  cloud:
    sentinel:
      enabled: true
      #不使用统一上下文名称
      web-context-unify: false
      transport:
        dashboard: ${SENTINEL-DASHBOARD:127.0.0.1:8718}